FROM node:22.23.2-alpine3.24

WORKDIR /app

COPY package.fixed.json ./package.json
COPY package-lock.fixed.json ./package-lock.json

RUN apk update && apk upgrade
RUN npm ci --omit=dev

COPY server.js ./server.js

ENV PORT=3000

EXPOSE 3000

USER node

CMD ["node", "server.js"]