apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: demoapp
spec:
  template:
    spec:
      containers:
        - name: demoapp
          image: host.rancher-desktop.internal:5001/demoapp:6af2848
